### ISSUE TITLE
Estimate MPP hours for minitest notebook

### ISSUE THREAD

**Issue by weaverba137** [desihub/two_percent_DESI#5]
It's good to have an estimate of the amount of time to run the minitest notebook, but it would also be good to have an estimate of the number of MPP hours needed as well.  It is possible that users with small allocations may burn though a significant fraction in just one run through.

**Comment by weaverba137** [comment]
Based on a run through the notebook yesterday, I got about 540 "raw core hours".  If that translates anything at all close to 1:1 to "MPP hours", then a single run of the notebook can burn through half a standard user's allocation.

**Comment by sbailey** [comment]
On cori the conversion factor is 2.5 so running the notebook once would exceed the default 1000 core hours.  That limit was purposefully small so that people would be purposeful in understanding the amount of time they are requesting, but we could make a larger default.  The default for developers known to be working at NERSC is 10k.  We could document this in the notebook as making sure that you have >1500 MPP hours available before starting.

Although this does sound like a lot for a test, note that this is only 10 tiles covered by 18 exposures, but that is 50000 targets = almost a week of e/BOSS running at full efficiency.

**Comment by sbailey** [comment]
On cori the conversion factor is 2.5 so running the notebook once would exceed the default 1000 core hours.  That limit was purposefully small so that people would be purposeful in understanding the amount of time they are requesting, but we could make a larger default.  The default for developers known to be working at NERSC is 10k.  We could document this in the notebook as making sure that you have >1500 MPP hours available before starting.

Although this does sound like a lot for a test, note that this is only 10 tiles covered by 18 exposures, but that is 50000 targets = almost a week of e/BOSS running at full efficiency.

**Comment by weaverba137** [comment]
For the record, I think the documentation added by #6 will be sufficient to close this issue.

**Comment by weaverba137** [comment]
Fixed in #6.
